### ISSUE TITLE
Create a Registration page backend - Java

### ISSUE THREAD

**Issue by vabby-123** [vabby-123/WeListen#2]

**Comment by Mohd-Farhan** [comment]
@vabby-123 I am interested. Can u assign it to me.

**Comment by AbhayNarayanPandey** [comment]
[form2.txt](https://github.com/vabby-123/WeListen/files/11926712/form2.txt)

**Comment by Tanmay0766** [comment]
[import javax.swing.;.txt](https://github.com/vabby-123/WeListen/files/11928952/import.javax.swing.txt)
